name: continuous-integration

on:
  push:
    branches:

permissions:
  contents: read

jobs:
  ci-go-lint:
    name: ci-go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - run: mkdir edition/static

      - uses: actions/cache@v6
        with:
          path: edition/static
          key: ${{ runner.os }}-static

      - name: Populate static/
        run: |
          rsync -av core/database/scripts edition/static/

      - uses: actions/setup-go@v7
        with:
          go-version: "1.23"
        id: go

      - uses: golangci/golangci-lint-action@v9

